packages:
  all:
  # note the compiler and providers specifications
  # only suggest a priority order, they do not exclude other options
  # suggested priority for compilers.
    compiler: [ gcc@11.2.0, cce@15.0.0, gcc@10.3.0 ,aocc@3.2.0 ]
    providers:
      mpi: [ cray-mpich ]
      pkgconfig: [ pkg-config ]
      fftw-api : [ cray-fftw ]
      blas: [cray-libsci ]
      lapack : [cray-libsci ]
      scalapack : [ cray-libsci ]

    permissions:
      read: world
      write: user

# don't build virtuals with an external provider
  mpi:
    buildable: False
  blas:
    buildable: False
  lapack:
    buildable: False
  scalapack:
    buildable: False
  fftw-api:
    buildable: False
  netcdf-cxx:
    buildable: False
  netcdf95:
    buildable: False

  netcdf-c:
    externals:
      - spec: netcdf-c@4.9.0.1+mpi%gcc
        modules:
          - cray-hdf5-parallel/1.12.2.1
          - cray-netcdf-hdf5parallel 
        prefix: /opt/cray/pe/netcdf-hdf5parallel/4.9.0.1/gnu/9.1
      - spec: netcdf-c@4.9.0.1+mpi%cee
        modules:
          - cray-hdf5-parallel/1.12.2.1
          - cray-netcdf-hdf5parallel 
        prefix: /opt/cray/pe/netcdf-hdf5parallel/4.9.0.1/crayclang/14.0
      - spec: netcdf-c@4.9.0.1+mpi%aocc
        modules:
          - cray-hdf5-parallel/1.12.2.1
          - cray-netcdf-hdf5parallel 
        prefix: /opt/cray/pe/netcdf-hdf5parallel/4.9.0.1/aocc/3.0
    
    buildable: False

  netcdf-fortran:
    externals:
      - spec: netcdf-fortran@4.9.0.1%gcc
        modules:
          - cray-hdf5-parallel/1.12.2.1
          - cray-netcdf-hdf5parallel 
        prefix: /opt/cray/pe/netcdf-hdf5parallel/4.9.0.1/gnu/9.1
      - spec: netcdf-fortran@4.9.0.1%cee
        modules:
          - cray-hdf5-parallel/1.12.2.1
          - cray-netcdf-hdf5parallel 
        prefix: /opt/cray/pe/netcdf-hdf5parallel/4.9.0.1/crayclang/14.0

      - spec: netcdf-fortran@4.9.0.1%aocc
        modules:
          - cray-hdf5-parallel/1.12.2.1
          - cray-netcdf-hdf5parallel 
        prefix: /opt/cray/pe/netcdf-hdf5parallel/4.9.0.1/aocc/3.0
      
    buildable: False

  netcdf-cxx4:
    externals:
      - spec: netcdf-cxx4@4.9.0.1%gcc
        modules:
          - cray-hdf5-parallel/1.12.2.1
          - cray-netcdf-hdf5parallel 
        prefix: /opt/cray/pe/netcdf-hdf5parallel/4.9.0.1/gnu/9.1
      - spec: netcdf-cxx4@4.9.0.1%cee
        modules:
          - cray-hdf5-parallel/1.12.2.1
          - cray-netcdf-hdf5parallel 
        prefix: /opt/cray/pe/netcdf-hdf5parallel/4.9.0.1/crayclang/14.0
      - spec: netcdf-cxx4@4.9.0.1%aocc
        modules:
          - cray-hdf5-parallel/1.12.2.1
          - cray-netcdf-hdf5parallel 
        prefix: /opt/cray/pe/netcdf-hdf5parallel/4.9.0.1/aocc/3.0
    
    buildable: False


  parallel-netcdf:
    externals:
      - spec: parallel-netcdf@1.12.3.1%gcc
        modules:
          - cray-parallel-netcdf/1.12.3.1
        prefix: /opt/cray/pe/parallel-netcdf/1.12.3.1/gnu/9.1
      - spec: parallel-netcdf@1.12.3.1%cee
        modules:
          - cray-parallel-netcdf/1.12.3.1
          - cray-netcdf-hdf5parallel 
        prefix: /opt/cray/pe/parallel-netcdf/1.12.3.1/crayclang/14.0
      - spec: parallel-netcdf@1.12.3.1%aocc
        modules:
          - cray-parallel-netcdf/1.12.3.1
        prefix: /opt/cray/pe/parallel-netcdf/1.12.3.1/aocc/3.0
    
    buildable: False

  cray-mpich:
    externals:
    - spec: cray-mpich@8.1.23%gcc
      modules:
      - cray-mpich/8.1.23
      - craype-network-ofi
      prefix: /opt/cray/pe/mpich/8.1.23/ofi/gnu/9.1  
    
    - spec: cray-mpich@8.1.23%aocc
      modules:
      - cray-mpich/8.1.23
      - craype-network-ofi
      prefix: /opt/cray/pe/mpich/8.1.23/ofi/aocc/3.0
    - spec: cray-mpich@8.1.23%cce
      modules:
      - cray-mpich/8.1.23
      - craype-network-ofi
      prefix: /opt/cray/pe/mpich/8.1.23/ofi/cray/10.0
    buildable: false

  

  hdf5:
    externals:
      - spec: hdf5@1.12.2.1+mpi%gcc
        modules:
          - cray-mpich/8.1.23
          - cray-hdf5-parallel/1.12.2.1 
        prefix: /opt/cray/pe/hdf5-parallel/1.12.2.1/gnu/9.1
      
      - spec: hdf5@1.12.2.1+mpi%cce
        modules:
          - cray-mpich/8.1.23
          - cray-hdf5-parallel/1.12.2.1 
        prefix: /opt/cray/pe/hdf5-parallel/1.12.2.1/cray-clang/14.0

      - spec: hdf5@1.12.2.1+mpi%aocc
        modules:
          - cray-mpich/8.1.23
          - cray-hdf5-parallel/1.12.2.1 
        prefix: /opt/cray/pe/hdf5-parallel/1.12.2.1/aocc/3.0
      

    buildable: False


  pkg-config:
    externals:
    - spec: pkg-config@0.29.2
      prefix: /usr
    buildable: false

  libfabric:
    externals:
    - spec: libfabric@1.12.1.2.2.0.0
      modules:
      - libfabric/1.12.1.2.2.0.0
      prefix: /opt/cray/libfabric/1.11.0.4.128
    buildable: false

  cray-fftw:
    externals:
    - spec: cray-fftw@3.3.10.3
      modules:
      - craype-x86-rome
      - cray-fftw/3.3.10.3
      prefix: /opt/cray/pe/fftw/3.3.10.3/x86_rome
    buildable: false
  

  cray-libsci:
    externals:
    - spec: cray-libsci@22.12.1.1%gcc
      modules:
      - cray-libsci/22.12.1.1
      prefix: /opt/cray/pe/libsci/22.12.1.1/gnu/9.1/x86_64
    - spec: cray-libsci@21.08.1.2%cce
      modules:
      - cray-libsci/22.12.1.1
      prefix: /opt/cray/pe/libsci/22.12.1.1/CRAY/9.0/x86_64
    - spec: cray-libsci@22.08.1.1%aocc
      modules:
      - cray-libsci/22.12.1.1
      prefix: /opt/cray/pe/libsci/22.12.1.1/AOCC/2.0/x86_64
  
  python:
    externals:
     - spec: python@3.9.13.1
       modules:
         - cray-python
       prefix:  /opt/cray/pe/python/3.9.13.1
    buildable: False
  
  py-numpy:
    externals:
     - spec: py-numpy@1.21.5
       modules:
         - cray-python
       prefix:  /opt/cray/pe/python/3.9.13.1
    buildable: False 
  

  py-mpi4py:
    externals:
     - spec: py-mpi4py@3.1.3
       modules:
         - cray-python
       prefix:  /opt/cray/pe/python/3.9.13.1
    buildable: False 
  
  py-scipy:
    externals:
     - spec: py-scipy@1.6.2
       modules:
         - cray-python
       prefix:  /opt/cray/pe/python/3.9.13.1
    buildable: False
  
  py-cython:
    externals:
     - spec: py-cython@0.29.28
       modules:
         - cray-python
       prefix:  /opt/cray/pe/python/3.9.13.1
    buildable: False
  py-pip:
    externals:
     - spec: py-pip@22.0.4
       modules:
         - cray-python
       prefix:  /opt/cray/pe/python/3.9.13.1
    buildable: False
  py-setuptools:
    externals:
     - spec: py-setuptools@58.1.0
       modules:
         - cray-python
       prefix:  /opt/cray/pe/python/3.9.13.1
    buildable: False
  
  
  
